from __future__ import annotations

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets.articulation import ArticulationCfg

from ..paths import ROBOT_ASSET_PATH

G1_INSPIRE_BASE_FIX_CFG = ArticulationCfg(
    spawn=sim_utils.UsdFileCfg(
        usd_path=ROBOT_ASSET_PATH.as_posix(),
        activate_contact_sensors=True,
        rigid_props=sim_utils.RigidBodyPropertiesCfg(
            disable_gravity=True,
            retain_accelerations=True,
            linear_damping=0.0,
            angular_damping=0.0,
            max_linear_velocity=1000.0,
            max_angular_velocity=1000.0,
            max_depenetration_velocity=1.0,
        ),
        articulation_props=sim_utils.ArticulationRootPropertiesCfg(
            enabled_self_collisions=False,
            solver_position_iteration_count=8,
            solver_velocity_iteration_count=4,
        ),
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 0.75),
        joint_pos={
            "left_hip_yaw_joint": 0.0,
            "left_hip_roll_joint": 0.0,
            "left_hip_pitch_joint": -0.05,
            "left_knee_joint": 0.2,
            "left_ankle_pitch_joint": -0.15,
            "left_ankle_roll_joint": 0.0,
            "right_hip_yaw_joint": 0.0,
            "right_hip_roll_joint": 0.0,
            "right_hip_pitch_joint": -0.05,
            "right_knee_joint": 0.2,
            "right_ankle_pitch_joint": -0.15,
            "right_ankle_roll_joint": 0.0,
            "waist_yaw_joint": 0.0,
            "waist_roll_joint": 0.0,
            "waist_pitch_joint": 0.0,
            "left_shoulder_pitch_joint": 0.0,
            "left_shoulder_roll_joint": 0.0,
            "left_shoulder_yaw_joint": 0.0,
            "left_elbow_joint": 0.0,
            "left_wrist_roll_joint": 0.0,
            "left_wrist_pitch_joint": 0.0,
            "left_wrist_yaw_joint": 0.0,
            "right_shoulder_pitch_joint": 0.0,
            "right_shoulder_roll_joint": 0.0,
            "right_shoulder_yaw_joint": 0.0,
            "right_elbow_joint": 0.0,
            "right_wrist_roll_joint": 0.0,
            "right_wrist_pitch_joint": 0.0,
            "right_wrist_yaw_joint": 0.0,
            "L_index_proximal_joint": 0.0,
            "L_index_intermediate_joint": 0.0,
            "L_middle_proximal_joint": 0.0,
            "L_middle_intermediate_joint": 0.0,
            "L_pinky_proximal_joint": 0.0,
            "L_pinky_intermediate_joint": 0.0,
            "L_ring_proximal_joint": 0.0,
            "L_ring_intermediate_joint": 0.0,
            "L_thumb_proximal_yaw_joint": 0.0,
            "L_thumb_proximal_pitch_joint": 0.0,
            "L_thumb_intermediate_joint": 0.0,
            "L_thumb_distal_joint": 0.0,
            "R_index_proximal_joint": 0.0,
            "R_index_intermediate_joint": 0.0,
            "R_middle_proximal_joint": 0.0,
            "R_middle_intermediate_joint": 0.0,
            "R_pinky_proximal_joint": 0.0,
            "R_pinky_intermediate_joint": 0.0,
            "R_ring_proximal_joint": 0.0,
            "R_ring_intermediate_joint": 0.0,
            "R_thumb_proximal_yaw_joint": 0.0,
            "R_thumb_proximal_pitch_joint": 0.0,
            "R_thumb_intermediate_joint": 0.0,
            "R_thumb_distal_joint": 0.0,
        },
        joint_vel={".*": 0.0},
    ),
    soft_joint_pos_limit_factor=0.9,
    actuators={
        "legs": ImplicitActuatorCfg(
            joint_names_expr=[".*_hip_yaw_joint", ".*_hip_roll_joint", ".*_hip_pitch_joint", ".*_knee_joint"],
            effort_limit=None,
            velocity_limit=None,
            stiffness={
                ".*_hip_yaw_joint": 400.0,
                ".*_hip_roll_joint": 400.0,
                ".*_hip_pitch_joint": 450.0,
                ".*_knee_joint": 550.0,
            },
            damping={
                ".*_hip_yaw_joint": 40.0,
                ".*_hip_roll_joint": 40.0,
                ".*_hip_pitch_joint": 45.0,
                ".*_knee_joint": 55.0,
            },
            armature=None,
        ),
        "waist": ImplicitActuatorCfg(
            joint_names_expr=["waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint"],
            effort_limit=1000.0,
            velocity_limit=0.0,
            stiffness={"waist_yaw_joint": 10000.0, "waist_roll_joint": 10000.0, "waist_pitch_joint": 10000.0},
            damping={"waist_yaw_joint": 10000.0, "waist_roll_joint": 10000.0, "waist_pitch_joint": 10000.0},
            armature=None,
        ),
        "feet": ImplicitActuatorCfg(
            joint_names_expr=[".*_ankle_pitch_joint", ".*_ankle_roll_joint"],
            effort_limit=None,
            stiffness={".*_ankle_pitch_joint": 250.0, ".*_ankle_roll_joint": 250.0},
            damping={".*_ankle_pitch_joint": 25.0, ".*_ankle_roll_joint": 25.0},
        ),
        "left_arm": ImplicitActuatorCfg(
            joint_names_expr=["left_shoulder_.*_joint", "left_elbow_joint", "left_wrist_.*_joint"],
            effort_limit=None,
            velocity_limit=None,
            stiffness={
                "left_shoulder_.*_joint": 120.0,
                "left_elbow_joint": 140.0,
                "left_wrist_.*_joint": 100.0,
            },
            damping={
                "left_shoulder_.*_joint": 12.0,
                "left_elbow_joint": 14.0,
                "left_wrist_.*_joint": 10.0,
            },
            armature=None,
        ),
        "right_arm": ImplicitActuatorCfg(
            joint_names_expr=["right_shoulder_.*_joint", "right_elbow_joint", "right_wrist_.*_joint"],
            effort_limit=None,
            velocity_limit=None,
            stiffness={
                "right_shoulder_.*_joint": 35.0,
                "right_elbow_joint": 55.0,
                "right_wrist_.*_joint": 45.0,
            },
            damping={
                "right_shoulder_.*_joint": 3.0,
                "right_elbow_joint": 3.5,
                "right_wrist_.*_joint": 3.0,
            },
            armature=None,
        ),
        "left_hand": ImplicitActuatorCfg(
            joint_names_expr=["L_.*"],
            effort_limit=100.0,
            velocity_limit=50.0,
            stiffness={".*": 1500.0},
            damping={".*": 20.0},
            armature={".*": 0.0},
        ),
        "right_hand": ImplicitActuatorCfg(
            joint_names_expr=[
                "R_index_proximal_joint",
                "R_index_intermediate_joint",
                "R_middle_proximal_joint",
                "R_middle_intermediate_joint",
                "R_pinky_proximal_joint",
                "R_pinky_intermediate_joint",
                "R_ring_proximal_joint",
                "R_ring_intermediate_joint",
                "R_thumb_proximal_yaw_joint",
                "R_thumb_proximal_pitch_joint",
                "R_thumb_intermediate_joint",
                "R_thumb_distal_joint",
            ],
            effort_limit=100.0,
            velocity_limit=50.0,
            stiffness={
                "R_index_proximal_joint": 1000.0,
                "R_index_intermediate_joint": 1000.0,
                "R_middle_proximal_joint": 1000.0,
                "R_middle_intermediate_joint": 1000.0,
                "R_pinky_proximal_joint": 1000.0,
                "R_pinky_intermediate_joint": 1000.0,
                "R_ring_proximal_joint": 1000.0,
                "R_ring_intermediate_joint": 1000.0,
                "R_thumb_proximal_yaw_joint": 1000.0,
                "R_thumb_proximal_pitch_joint": 1000.0,
                "R_thumb_intermediate_joint": 1000.0,
                "R_thumb_distal_joint": 1000.0,
            },
            damping={
                "R_index_proximal_joint": 15.0,
                "R_index_intermediate_joint": 15.0,
                "R_middle_proximal_joint": 15.0,
                "R_middle_intermediate_joint": 15.0,
                "R_pinky_proximal_joint": 15.0,
                "R_pinky_intermediate_joint": 15.0,
                "R_ring_proximal_joint": 15.0,
                "R_ring_intermediate_joint": 15.0,
                "R_thumb_proximal_yaw_joint": 15.0,
                "R_thumb_proximal_pitch_joint": 15.0,
                "R_thumb_intermediate_joint": 15.0,
                "R_thumb_distal_joint": 15.0,
            },
            armature={".*": 0.0},
        ),
    },
)
